### ISSUE TITLE
Reorder in grid?

### ISSUE THREAD

**Issue by thomax** [bokuweb/react-sortable-pane#38]
I have an array of images, each represented by a pane, which I want to lay out in a floating grid, and then allow reordering by dragging left/right and also up/down. Is this possible in the current implementation? If not, will you consider this a worthy feature?

**Comment by bokuweb** [comment]
@thomax Currently it is not possible.but I want to be able to future

**Comment by IanVS** [comment]
I would suggest keeping this package simple (constrained to horizontal _or_ vertical).  Once you get into two different directions, things get significantly more complicated.  There are already packages which do this, for example [react-grid-layout](https://github.com/STRML/react-grid-layout).  I've chosen to use this package particularly because it does _not_ support a grid.

**Comment by bokuweb** [comment]
@IanVS thanks!! I support your thinking.
